# Generated by Django 5.0.6 on 2024-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'Rejected')], default=1),
        ),
    ]
